/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

// Commented out due to SSL certificate issues - optional plugin
// plugins {
//     // Apply the foojay-resolver plugin to allow automatic download of JDKs
//     id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
// }

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "EspressoFramework"
include("app")
